name: CI/CD configure tutorial
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Installing node_modules
        run: npm install
      - name: Running Prettier
        run: npm run prettier
      - name: Running Linter
        run: npm run lint
      - name: Running tests
        run: npm run test
      - run: echo "🍏 This job's status is ${{ job.status }}."
