name: CI/CD configure tutorial
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: installing node_modules
        run: npm install
      - name: running Prettier
        run: npm run prettier
      - name: running Linter
        run: npm run lint
      - name: running tests
        run: npm run test
      - run: echo "This job's status is ${{ job.status }}."
